# Google Cloud Build configuration for Opus Agent
# This file defines the build steps for deploying to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/opus-agent:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/opus-agent:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/opus-agent:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/opus-agent:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'opus-agent'
      - '--image=gcr.io/$PROJECT_ID/opus-agent:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--concurrency=1000'
      - '--max-instances=10'
      - '--set-env-vars=ENV=production,PORT=8000,HOST=0.0.0.0'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/opus-agent:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/opus-agent:latest'

# Timeout for the entire build
timeout: '1200s'

# Options for the build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY 